"""add missing task columns

Revision ID: 0fc2b31d22c1
Revises: 
Create Date: 2026-09-07 20:07:19.442015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fc2b31d22c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('architecture', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('backend_code', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('frontend_code', sa.Text(), nullable=True))
    op.drop_column('tasks', 'generated_code')
    op.drop_column('tasks', 'plan')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('plan', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tasks', sa.Column('generated_code', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'frontend_code')
    op.drop_column('tasks', 'backend_code')
    op.drop_column('tasks', 'architecture')
    # ### end Alembic commands ###
