"""Static, known-good project scaffolding for VeriReview exports.

The LLM generates *source* files; this module provides everything around
them so the downloaded ZIP runs with minimal friction: build files,
app config wired to env vars, .env/.env.example, .gitignore,
docker-compose, runnable frontend shell, README and preview page.
"""

import io
import json
import zipfile

DEFAULT_DB_URL = "postgresql://app:appsecret@db:5432/appdb"

FAMILY_PORT = {
    "spring": "8080",
    "django": "8000",
    "python": "5000",
    "node": "3000",
    "generic": "8000",
}


def sanitize_relpath(name: str) -> str:
    parts = []
    for part in (name or "unnamed.txt").replace("\\", "/").split("/"):
        part = part.strip()
        if not part or part in (".", ".."):
            continue
        parts.append(part)
    return "/".join(parts) or "unnamed.txt"


def backend_zip_path(family: str, filename: str) -> str:
    rel = sanitize_relpath(filename)
    if rel.startswith("backend/"):
        rel = rel[len("backend/"):]
    if family == "spring":
        # Java sources live under the Maven layout (basename, as before).
        base = rel.split("/")[-1] or "Main.java"
        return f"backend/src/main/java/{base}"
    return f"backend/{rel}"


def _env_lines(db_url: str, api_keys: dict, port: str, example: bool) -> str:
    lines = [
        "# Generated by VeriReview. Copy to .env and adjust before running."
        if example else
        "# Generated by VeriReview for this run. Keep secret, do not commit."
    ]
    if example:
        lines.append("# DATABASE_URL=postgresql://app:appsecret@db:5432/appdb")
        lines.append(f"# PORT={port}")
        for key in sorted((api_keys or {}).keys()):
            lines.append(f"# {key}=your-{key.lower()}-here")
        if not api_keys:
            lines.append("# EXTRA_API_KEY=your-key-here")
    else:
        lines.append(f"DATABASE_URL={db_url or DEFAULT_DB_URL}")
        lines.append(f"PORT={port}")
        for key in sorted((api_keys or {}).keys()):
            lines.append(f"{key}={api_keys[key]}")
    return "\n".join(lines) + "\n"


GITIGNORE = """# VeriReview export
.env
node_modules/
__pycache__/
*.pyc
.venv/
target/
dist/
.DS_Store
*.log
"""

FRONTEND_PACKAGE_JSON = """{
  "name": "verireview-frontend-app",
  "private": true,
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^4.3.1",
    "vite": "^5.4.0"
  }
}
"""

FRONTEND_VITE_CONFIG = """import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  server: { port: 5173 }
})
"""

FRONTEND_INDEX_HTML = """<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>VeriReview App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
"""

FRONTEND_MAIN_JSX = """import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)
"""

FRONTEND_INDEX_CSS = """body { margin: 0; font-family: system-ui, sans-serif; }
#root { max-width: 1100px; margin: 0 auto; padding: 24px; }
"""


def static_frontend_files() -> dict:
    return {
        "frontend/package.json": FRONTEND_PACKAGE_JSON,
        "frontend/vite.config.js": FRONTEND_VITE_CONFIG,
        "frontend/index.html": FRONTEND_INDEX_HTML,
        "frontend/src/main.jsx": FRONTEND_MAIN_JSX,
        "frontend/src/index.css": FRONTEND_INDEX_CSS,
    }


SPRING_POM = """<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.2.5</version>
  </parent>
  <groupId>com.verireview</groupId>
  <artifactId>app</artifactId>
  <version>1.0.0</version>
  <properties>
    <java.version>17</java.version>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-validation</artifactId>
    </dependency>
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>
"""

SPRING_PROPERTIES = """server.port=8080
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/appdb}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
"""

SPRING_DOCKERFILE = """FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /build
COPY backend/pom.xml .
COPY backend/src ./src
RUN mvn -q package -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /build/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
"""

DJANGO_REQUIREMENTS = """django>=5.0,<6.0
djangorestframework>=3.15
psycopg[binary]>=3.1
django-cors-headers>=4.3
gunicorn>=22.0
python-dotenv>=1.0
dj-database-url>=2.1
"""

DJANGO_DOCKERFILE = """FROM python:3.11-slim
WORKDIR /app
COPY backend/requirements.txt ./backend/requirements.txt
RUN pip install --no-cache-dir -r backend/requirements.txt
COPY backend ./backend
COPY .env .env
EXPOSE 8000
CMD ["sh", "-c", "python backend/manage.py migrate --noinput && python backend/manage.py runserver 0.0.0.0:8000"]
"""

PYTHON_REQUIREMENTS = """flask>=3.0
fastapi>=0.110
uvicorn[standard]>=0.29
sqlalchemy>=2.0
psycopg2-binary>=2.9
python-dotenv>=1.0
flask-cors>=4.0
gunicorn>=22.0
"""

PYTHON_DOCKERFILE = """FROM python:3.11-slim
WORKDIR /app
COPY backend/requirements.txt ./backend/requirements.txt
RUN pip install --no-cache-dir -r backend/requirements.txt
COPY backend ./backend
COPY .env .env
EXPOSE 5000
CMD ["python", "backend/app.py"]
"""

NODE_PACKAGE_JSON = """{
  "name": "verireview-backend",
  "version": "1.0.0",
  "type": "commonjs",
  "scripts": {
    "start": "node server.js"
  },
  "dependencies": {
    "cors": "^2.8.5",
    "dotenv": "^16.4.5",
    "express": "^4.19.2",
    "pg": "^8.12.0"
  }
}
"""

NODE_DOCKERFILE = """FROM node:20-slim
WORKDIR /app
COPY backend/package.json ./backend/package.json
RUN npm install --prefix backend --omit=dev
COPY backend ./backend
COPY .env .env
EXPOSE 3000
CMD ["npm", "start", "--prefix", "backend"]
"""

GENERIC_DOCKERFILE = """FROM python:3.11-slim
WORKDIR /app
COPY backend/ ./backend/
COPY .env .env
EXPOSE 8000
CMD ["sh", "-c", "if [ -f backend/requirements.txt ]; then pip install --no-cache-dir -r backend/requirements.txt; fi; python backend/app.py"]
"""


def static_backend_files(family: str) -> dict:
    if family == "spring":
        return {
            "backend/pom.xml": SPRING_POM,
            "backend/src/main/resources/application.properties": SPRING_PROPERTIES,
        }
    if family == "django":
        return {"backend/requirements.txt": DJANGO_REQUIREMENTS}
    if family == "python":
        return {"backend/requirements.txt": PYTHON_REQUIREMENTS}
    if family == "node":
        return {"backend/package.json": NODE_PACKAGE_JSON}
    return {}


def dockerfile_for(family: str) -> str:
    return {
        "spring": SPRING_DOCKERFILE,
        "django": DJANGO_DOCKERFILE,
        "python": PYTHON_DOCKERFILE,
        "node": NODE_DOCKERFILE,
    }.get(family, GENERIC_DOCKERFILE)


def docker_compose_for(family: str) -> str:
    port = FAMILY_PORT.get(family, "8000")
    return f"""services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: app
      POSTGRES_PASSWORD: appsecret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    env_file:
      - .env
    ports:
      - "{port}:{port}"
    depends_on:
      - db
volumes:
  pgdata: {{}}
"""


def readme_for(task, tech_stack, family, db_url, api_keys, test_passed,
               requirements_met, findings_count, revision_count) -> str:
    port = FAMILY_PORT.get(family, "8000")
    backend_run = {
        "spring": "cd backend && mvn spring-boot:run  # needs Java 17 + Maven",
        "django": "cd backend && pip install -r requirements.txt && python manage.py migrate && python manage.py runserver",
        "python": "cd backend && pip install -r requirements.txt && python app.py  # adjust entrypoint if yours differs",
        "node": "cd backend && npm install && npm start  # entrypoint: server.js",
        "generic": "cd backend  # see source files; install your runtime deps, then run the entrypoint",
    }[family]
    key_rows = "\n".join(f"| `{k}` | API key used by the app |" for k in sorted((api_keys or {}).keys()))
    env_table = (
        "| Name | Purpose |\n| --- | --- |\n"
        f"| `DATABASE_URL` | Postgres connection string{' (provided)' if db_url else ''} |\n"
        f"| `PORT` | App port (default {port}) |\n" + (key_rows + "\n" if key_rows else "")
    )
    title = (task or "VeriReview project").strip().split("\n")[0][:100]
    verdict = (
        "PASS" if (test_passed and requirements_met and not findings_count) else "NEEDS ATTENTION"
    )
    return f"""# {title}

Generated by **VeriReview** — Tech stack: **{tech_stack}** — Verification: **{verdict}**
(Test {'PASS' if test_passed else 'FAIL'} · Verify {'PASS' if requirements_met else 'FAIL'} · "
f"{findings_count} finding(s) · {revision_count} fix round(s))

## Project structure

```text
backend/    # generated {tech_stack} backend (+ build files)
frontend/   # React + Vite UI (src/App.jsx is the generated screen)
preview.html# open-in-browser preview of the UI (mocked API data)
.env        # your runtime secrets (DO NOT commit)
.env.example# template for collaborators
docker-compose.yml # app + Postgres with one command
Dockerfile  # production-ish container for the backend
```

## 1) Configure secrets

Secrets were requested when the task ran and baked into `.env`:

```bash
cp .env.example .env   # if you need to reset, then edit values
```

{env_table}
## 2) Run everything with Docker (recommended)

```bash
docker compose up --build
# backend -> http://localhost:{port} | frontend (dev) -> see below
```

## 3) Run locally (backend + frontend)

```bash
# Backend
{backend_run}

# Frontend (new terminal)
cd frontend && npm install && npm run dev
# open http://localhost:5173
```

## 4) Preview without running anything

Open `preview.html` in a browser — it renders `frontend/src/App.jsx` with mocked API data.

## Notes

- `.env` is git-ignored; share only `.env.example`.
- If the backend entrypoint filename differs from the scaffold default, adjust `Dockerfile` CMD / compose command.
"""


def build_project_zip(task, tech_stack, family, backend_code, frontend_code,
                      documentation, deployment_config, db_url, api_keys,
                      test_report, verification_report, test_passed,
                      requirements_met, verified_findings, revision_count,
                      record_id, preview_html) -> bytes:
    from app.file_utils import parse_files

    port = FAMILY_PORT.get(family, "8000")
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("README.md", documentation or f"# {task}\n")
        zf.writestr("PROJECT_README.md", readme_for(
            task, tech_stack, family, db_url, api_keys, test_passed,
            requirements_met, len(verified_findings or []), revision_count or 0))
        zf.writestr("Dockerfile", dockerfile_for(family))
        zf.writestr("deployment/Dockerfile.llm", deployment_config or "# no deployment config generated\n")
        zf.writestr("docker-compose.yml", docker_compose_for(family))
        zf.writestr(".gitignore", GITIGNORE)
        zf.writestr(".env", _env_lines(db_url, api_keys, port, example=False))
        zf.writestr(".env.example", _env_lines(db_url, api_keys, port, example=True))
        zf.writestr("project.json", json.dumps({
            "id": record_id,
            "task": task,
            "tech_stack": tech_stack,
            "stack_family": family,
            "status": "completed",
            "test_passed": test_passed,
            "requirements_met": requirements_met,
            "revision_count": revision_count,
            "verified_findings": verified_findings or [],
            "test_report": test_report or "",
            "verification_report": verification_report or "",
            "db_configured": bool(db_url),
            "api_key_names": sorted((api_keys or {}).keys()),
        }, indent=2))

        zf.writestr("backend/README.txt",
                    f"Generated {tech_stack} backend.\n"
                    "Install notes live in PROJECT_README.md.\n")
        for filename, content in parse_files(backend_code or "").items():
            zf.writestr(backend_zip_path(family, filename), content or "")
        for path, content in static_backend_files(family).items():
            zf.writestr(path, content)

        for path, content in static_frontend_files().items():
            zf.writestr(path, content)
        zf.writestr("frontend/src/App.jsx", frontend_code or "// No frontend generated\n")

        zf.writestr("preview.html", preview_html)
        zf.writestr("frontend/preview.html", preview_html)
        zf.writestr("HOW_TO_PREVIEW.txt",
                    "To see the generated UI:\n"
                    "1. Unzip this file.\n"
                    "2. Open preview.html (or frontend/preview.html) in your browser.\n"
                    "   It renders frontend/src/App.jsx with mocked API data.\n"
                    "3. To run the real project, follow PROJECT_README.md.\n")
    buffer.seek(0)
    return buffer.getvalue()
